# yaml-language-server: $schema=https://raw.githubusercontent.com/mui/toolpad/v0.10.0/docs/schemas/v1/definitions.json#properties/Page

apiVersion: v1
kind: page
spec:
  title: pageContacts
  display: shell
  authorization:
    allowAll: true
  maxWidth: lg
  content:
    - component: PageRow
      name: pageRow
      props:
        justifyContent: start
      children:
        - component: Button
          name: button1
          props:
            content: BACK
            variant: outlined
          layout:
            columnSize: 0.23067430888950213
        - component: Button
          name: button
          layout:
            columnSize: 0.22716936744852587
          props:
            content: SAVE
            variant: outlined
        - component: Button
          name: button2
          layout:
            columnSize: 0.46877933092678215
          props:
            content: +NEW CONTACT
            variant: outlined
        - component: Button
          name: button3
          layout:
            columnSize: 3.07337699273519
          props:
            content: Edit
            variant: outlined
    - component: Text
      name: text
      props:
        mode: text
        value: Segmentation
        variant: h6
        loading: false
      layout:
        horizontalAlign: center
        verticalAlign: center
    - component: DataGrid
      name: dataGrid1
